### ISSUE TITLE
How were Nova campaign files extracted?

### ISSUE THREAD

**Issue by boaz23** [abrahamYG/SC2GameData#4]
Since the aforementioned files in the title are encrypted, I would like to know how did you manage to extract it.
Tagging @folknor specifically since he's the one who committed those files, so he probably has the answer.

**Comment by folknor** [comment]
Oh, hmm. It's a few years ago now but if I remember correctly, here's how it went:

The Nova campaign data is encrypted on disk, and someone hacked it open and illegally made the files available on the internet somewhere. "Everyone" on the SC2 modding Discord knew how to get a hold of the files anyway, and Blizzard employees were active on the server. So after quite some time I just said "fuck it", essentially, and committed it to git even though the official files still remained encrypted (I don't know if they still are, but probably).

This is why my original commit message is worded like it is: `Commit Nova story assets. It's useful data, and the campaign has been out for a long time, and people on the discord have the data anyway.`

For the rest of the data I just used the lua script I wrote which is still in the repo. I have no idea if that still works.

**Comment by abrahamYG** [comment]
They are still encrytped but someone on the discord found the key a few months ago, so if you want to extract them more up to date, you can check on the discrod. I will see to update the files some time (nstory.sc2map wasnt extarcted and current versions on the repo were not updated for 5.0 achievements.)

also wlecome @folknor

**Comment by abrahamYG** [comment]
Aslo this shoudl have been posted on the mapster fork :P

**Comment by boaz23** [comment]
Hmm very interesting, thank you.
